version: "3.8"

services:
  php:
    container_name: api_jalix_manager
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    working_dir: /app
    volumes:
      - ./:/app
  nginx:
    container_name: nginx_jalix_manager
    build:
      context: ./docker/nginx
    working_dir: /app
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
      - ./:/app:cached
    depends_on:
      - php